---
app_name: Synfy
config:
  playlists_to_download: Liked Songs~Liked Albums~Mix 1
  playlists_config: \{year}\{artists} - {title}~\{year}\{artists} - {title}~\{artists} - {title}
  playlists_m3u: True~True~True
spotify:
  client_id: "84cb72428eba411495f7599023c8c8da"
  client_secret: "543a55fed80145bfbe195ea42ff7c6ba"
  redirect_uri: http://localhost:5000/callback
  scope: user-library-read playlist-modify-private playlist-read-private playlist-read-collaborative user-follow-read user-read-playback-state user-modify-playback-state user-read-private user-read-email
  playlist_liked_songs: Liked Songs
  playlist_liked_albums: Liked Albums
author: matthieu pierson
